<a href="https://colab.research.google.com/github/kaonashithank1022/data-analysis-basic-kadai/blob/main/text/7%E7%AB%A0_pandas%E3%82%92%E4%BD%BF%E3%81%84%E3%81%93%E3%81%AA%E3%81%9D%E3%81%86.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [14]:
# pandasライブラリを読み込む
import pandas as pd

# csvファイルを読み込む（データフレームとして呼び出される）
df = pd.read_csv('train.csv')
# 先頭から5行目までのデータを表示する
df.head()

,POSTED_BY,UNDER_CONSTRUCTION,RERA,BHK_NO.,BHK_OR_RK,SQUARE_FT,READY_TO_MOVE,RESALE,ADDRESS,LONGITUDE,LATITUDE,TARGET(PRICE_IN_LACS)
0,Owner,0,0,2,BHK,1300.236407,1,1,"Ksfc Layout,Bangalore",12.969910,77.597960,55.0
1,Dealer,0,0,2,BHK,1275.000000,1,1,"Vishweshwara Nagar,Mysore",12.274538,76.644605,51.0
2,Owner,0,0,2,BHK,933.159722,1,1,"Jigani,Bangalore",12.778033,77.632191,43.0
3,Owner,0,1,2,BHK,929.921143,1,1,"Sector-1 Vaishali,Ghaziabad",28.642300,77.344500,62.5
4,Dealer,1,0,2,BHK,999.009247,0,1,"New Town,Kolkata",22.592200,88.484911,60.5

In [15]:
# Pythonはインデックスが0から始まるので、
# 3行目を指定するときは1を足して2になります。
df.loc[[2]]

,POSTED_BY,UNDER_CONSTRUCTION,RERA,BHK_NO.,BHK_OR_RK,SQUARE_FT,READY_TO_MOVE,RESALE,ADDRESS,LONGITUDE,LATITUDE,TARGET(PRICE_IN_LACS)
2,Owner,0,0,2,BHK,933.159722,1,1,"Jigani,Bangalore",12.778033,77.632191,43.0

In [16]:
df.query('POSTED_BY == "Owner"')

,POSTED_BY,UNDER_CONSTRUCTION,RERA,BHK_NO.,BHK_OR_RK,SQUARE_FT,READY_TO_MOVE,RESALE,ADDRESS,LONGITUDE,LATITUDE,TARGET(PRICE_IN_LACS)
0,Owner,0,0,2,BHK,1300.236407,1,1,"Ksfc Layout,Bangalore",12.969910,77.597960,55.0
2,Owner,0,0,2,BHK,933.159722,1,1,"Jigani,Bangalore",12.778033,77.632191,43.0
3,Owner,0,1,2,BHK,929.921143,1,1,"Sector-1 Vaishali,Ghaziabad",28.642300,77.344500,62.5
5,Owner,0,0,3,BHK,1250.000000,1,1,"South Chittoor,Kochi",10.033280,76.282571,42.0
7,Owner,0,1,3,BHK,1181.012946,1,1,"Kharar,Mohali",30.740000,76.650000,52.0
...,...,...,...,...,...,...,...,...,...,...,...,...
29441,Owner,0,0,3,BHK,1500.375094,1,1,"Sector 57 Faridabad,Faridabad",28.320000,77.289381,40.0
29445,Owner,0,0,2,BHK,1062.134891,1,1,"Tilakwadi,Belgaum",15.866670,74.500000,40.0
29446,Owner,0,0,3,BHK,2500.000000,1,1,"Shamshabad Road,Agra",27.140626,78.043277,45.0
29447,Owner,0,0,2,BHK,769.230769,1,1,"E3-108, Lake View Recidency,,Vapi",39.945409,-86.150721,16.0
29449,Owner,0,0,2,BHK,927.079009,1,1,"Sholinganallur,Chennai",12.900150,80.227910,67.0

In [17]:
df.loc[[df['TARGET(PRICE_IN_LACS)'].idxmax()]]

,POSTED_BY,UNDER_CONSTRUCTION,RERA,BHK_NO.,BHK_OR_RK,SQUARE_FT,READY_TO_MOVE,RESALE,ADDRESS,LONGITUDE,LATITUDE,TARGET(PRICE_IN_LACS)
11238,Dealer,0,0,3,BHK,187500000.0,1,1,"R.T. Nagar,Bangalore",13.0189,77.5963,30000.0

In [18]:
# 物件価格の最大を求める
df['TARGET(PRICE_IN_LACS)'].max()

30000.0

In [19]:
# 物件価格の最小を求める
df['TARGET(PRICE_IN_LACS)'].min()

0.25

In [20]:
# 物件価格の平均を求める
df['TARGET(PRICE_IN_LACS)'].mean()

np.float64(142.8987457132186)

In [21]:
df['TARGET(PRICE_IN_LACS)'].describe()

count    29451.000000
mean       142.898746
std        656.880713
min          0.250000
25%         38.000000
50%         62.000000
75%        100.000000
max      30000.000000
Name: TARGET(PRICE_IN_LACS), dtype: float64

In [22]:
df['TARGET(PRICE_IN_LACS)'].describe()

count    29451.000000
mean       142.898746
std        656.880713
min          0.250000
25%         38.000000
50%         62.000000
75%        100.000000
max      30000.000000
Name: TARGET(PRICE_IN_LACS), dtype: float64

In [23]:
# 初回のみライブラリをインポートする
import pandas as pd

# csvファイルをデータフレームとして読み込む
df = pd.read_csv("sample_pandas_6.csv")
# 先頭から5行目までを表示する
df.head()

          発注日      商品番号              商品名   単価  在庫  注文数
0  2016-03-06  YY4HAAZR  商品サンプル YY4HAAZR  780  20   24
1  2015-03-27  Z4WOOIYV  商品サンプル Z4WOOIYV   90  45   12
2  2017-05-31  YY4HAAZR  商品サンプル YY4HAAZR  780  10    0
3  2022-10-26  1QJFO8QY  商品サンプル 1QJFO8QY  600   5   24
4  2016-06-10  1QJFO8QY  商品サンプル 1QJFO8QY  600  40   24

In [24]:
df.query('商品番号 == "Z4WOOIYV"')

            発注日      商品番号              商品名  単価  在庫  注文数
1    2015-03-27  Z4WOOIYV  商品サンプル Z4WOOIYV  90  45   12
5    2024-04-12  Z4WOOIYV  商品サンプル Z4WOOIYV  90  35   24
24   2020-05-08  Z4WOOIYV  商品サンプル Z4WOOIYV  90  10   36
25   2022-03-21  Z4WOOIYV  商品サンプル Z4WOOIYV  90  15   54
32   2023-12-16  Z4WOOIYV  商品サンプル Z4WOOIYV  90   0    6
36   2024-08-29  Z4WOOIYV  商品サンプル Z4WOOIYV  90  35    0
54   2023-11-07  Z4WOOIYV  商品サンプル Z4WOOIYV  90  25   48
59   2020-05-03  Z4WOOIYV  商品サンプル Z4WOOIYV  90  20   42
67   2022-10-24  Z4WOOIYV  商品サンプル Z4WOOIYV  90   5   24
71   2017-10-09  Z4WOOIYV  商品サンプル Z4WOOIYV  90  45   54
73   2023-12-30  Z4WOOIYV  商品サンプル Z4WOOIYV  90  25   12
87   2022-09-06  Z4WOOIYV  商品サンプル Z4WOOIYV  90  10    6
93   2021-12-11  Z4WOOIYV  商品サンプル Z4WOOIYV  90   0    0
116  2016-11-07  Z4WOOIYV  商品サンプル Z4WOOIYV  90  25   30
120  2020-02-12  Z4WOOIYV  商品サンプル Z4WOOIYV  90  50   24
125  2018-12-05  Z4WOOIYV  商品サンプル Z4WOOIYV  90  25    0
130  2018-06-25  Z4WOOIYV  商品サンプル Z4WOOIYV  90  30   12
140  2016-02-21  Z4WOOIYV  商品サンプル Z4WOOIYV  90  20   60
143  2023-12-10  Z4WOOIYV  商品サンプル Z4WOOIYV  90  35   30
158  2019-04-05  Z4WOOIYV  商品サンプル Z4WOOIYV  90   0   42
171  2016-01-30  Z4WOOIYV  商品サンプル Z4WOOIYV  90   5   48
177  2023-10-19  Z4WOOIYV  商品サンプル Z4WOOIYV  90   5   24

In [25]:
df.query('単価 == 600')

            発注日      商品番号              商品名   単価  在庫  注文数
3    2022-10-26  1QJFO8QY  商品サンプル 1QJFO8QY  600   5   24
4    2016-06-10  1QJFO8QY  商品サンプル 1QJFO8QY  600  40   24
8    2021-03-10  1QJFO8QY  商品サンプル 1QJFO8QY  600  25   48
13   2022-03-21  1QJFO8QY  商品サンプル 1QJFO8QY  600  15   48
18   2018-04-25  1QJFO8QY  商品サンプル 1QJFO8QY  600  45   48
29   2018-11-12  1QJFO8QY  商品サンプル 1QJFO8QY  600  45   60
57   2022-01-29  1QJFO8QY  商品サンプル 1QJFO8QY  600  50   60
58   2024-12-23  1QJFO8QY  商品サンプル 1QJFO8QY  600  25   18
69   2018-09-04  1QJFO8QY  商品サンプル 1QJFO8QY  600  40   48
72   2020-08-12  1QJFO8QY  商品サンプル 1QJFO8QY  600  10   12
83   2024-11-27  1QJFO8QY  商品サンプル 1QJFO8QY  600  15   36
94   2016-11-11  1QJFO8QY  商品サンプル 1QJFO8QY  600  10    0
95   2023-03-12  1QJFO8QY  商品サンプル 1QJFO8QY  600  30   30
102  2023-08-15  1QJFO8QY  商品サンプル 1QJFO8QY  600  30   24
110  2016-12-18  1QJFO8QY  商品サンプル 1QJFO8QY  600   5   24
112  2017-11-25  1QJFO8QY  商品サンプル 1QJFO8QY  600  50   36
113  2017-02-22  1QJFO8QY  商品サンプル 1QJFO8QY  600  35    6
126  2015-09-22  1QJFO8QY  商品サンプル 1QJFO8QY  600  40   30
133  2020-10-17  1QJFO8QY  商品サンプル 1QJFO8QY  600   0   24
138  2023-05-20  1QJFO8QY  商品サンプル 1QJFO8QY  600  25   12
139  2023-03-12  1QJFO8QY  商品サンプル 1QJFO8QY  600  25    0
149  2015-03-20  1QJFO8QY  商品サンプル 1QJFO8QY  600  40   36
151  2021-11-27  1QJFO8QY  商品サンプル 1QJFO8QY  600  50   54
153  2015-10-14  1QJFO8QY  商品サンプル 1QJFO8QY  600  35   54
159  2021-08-20  1QJFO8QY  商品サンプル 1QJFO8QY  600  50   12
163  2020-11-22  1QJFO8QY  商品サンプル 1QJFO8QY  600  35   54
169  2017-05-14  1QJFO8QY  商品サンプル 1QJFO8QY  600  20   54
170  2020-04-19  1QJFO8QY  商品サンプル 1QJFO8QY  600   5   54
181  2017-11-15  1QJFO8QY  商品サンプル 1QJFO8QY  600  25   48
191  2018-05-27  1QJFO8QY  商品サンプル 1QJFO8QY  600  50   48
193  2018-11-16  1QJFO8QY  商品サンプル 1QJFO8QY  600   5   60
195  2021-08-02  1QJFO8QY  商品サンプル 1QJFO8QY  600  10   42

In [26]:
df.query('在庫 <= 5')

            発注日      商品番号              商品名   単価  在庫  注文数
3    2022-10-26  1QJFO8QY  商品サンプル 1QJFO8QY  600   5   24
14   2018-11-08  48XMJXKO  商品サンプル 48XMJXKO  330   5   30
19   2016-09-15  YY4HAAZR  商品サンプル YY4HAAZR  780   5   54
32   2023-12-16  Z4WOOIYV  商品サンプル Z4WOOIYV   90   0    6
35   2018-01-03  QRMOGNUU  商品サンプル QRMOGNUU  420   0   54
41   2022-11-30  MESUDVWQ  商品サンプル MESUDVWQ  660   0   54
63   2019-09-14  2HSTCDWM  商品サンプル 2HSTCDWM  300   5   30
67   2022-10-24  Z4WOOIYV  商品サンプル Z4WOOIYV   90   5   24
76   2018-12-28  YY4HAAZR  商品サンプル YY4HAAZR  780   0   42
77   2019-11-27  2HSTCDWM  商品サンプル 2HSTCDWM  300   5    0
81   2023-03-07  MESUDVWQ  商品サンプル MESUDVWQ  660   5   18
82   2019-09-26  QRMOGNUU  商品サンプル QRMOGNUU  420   5   30
92   2020-02-03  X0ZE2ZMY  商品サンプル X0ZE2ZMY   90   0    0
93   2021-12-11  Z4WOOIYV  商品サンプル Z4WOOIYV   90   0    0
97   2017-01-29  48XMJXKO  商品サンプル 48XMJXKO  330   5   24
100  2016-12-04  48XMJXKO  商品サンプル 48XMJXKO  330   0    6
110  2016-12-18  1QJFO8QY  商品サンプル 1QJFO8QY  600   5   24
114  2024-07-29  YY4HAAZR  商品サンプル YY4HAAZR  780   5   48
117  2024-12-26  S6RE8W6X  商品サンプル S6RE8W6X  720   0   54
118  2018-07-27  S6RE8W6X  商品サンプル S6RE8W6X  720   0   24
119  2018-05-17  QRMOGNUU  商品サンプル QRMOGNUU  420   0   48
129  2024-03-12  QRMOGNUU  商品サンプル QRMOGNUU  420   5   12
131  2021-03-27  8T7D5DQA  商品サンプル 8T7D5DQA  120   0   42
133  2020-10-17  1QJFO8QY  商品サンプル 1QJFO8QY  600   0   24
155  2015-05-24  S6RE8W6X  商品サンプル S6RE8W6X  720   5   60
158  2019-04-05  Z4WOOIYV  商品サンプル Z4WOOIYV   90   0   42
165  2018-04-08  MESUDVWQ  商品サンプル MESUDVWQ  660   5   48
170  2020-04-19  1QJFO8QY  商品サンプル 1QJFO8QY  600   5   54
171  2016-01-30  Z4WOOIYV  商品サンプル Z4WOOIYV   90   5   48
172  2019-06-06  QRMOGNUU  商品サンプル QRMOGNUU  420   5   54
177  2023-10-19  Z4WOOIYV  商品サンプル Z4WOOIYV   90   5   24
182  2015-02-08  2HSTCDWM  商品サンプル 2HSTCDWM  300   5    0
193  2018-11-16  1QJFO8QY  商品サンプル 1QJFO8QY  600   5   60
199  2016-08-07  8T7D5DQA  商品サンプル 8T7D5DQA  120   0   42

In [27]:
df.query('商品番号 == "8T7D5DQA" and 在庫 <= 5')

            発注日      商品番号              商品名   単価  在庫  注文数
131  2021-03-27  8T7D5DQA  商品サンプル 8T7D5DQA  120   0   42
199  2016-08-07  8T7D5DQA  商品サンプル 8T7D5DQA  120   0   42

In [28]:
def tax(x):
    return x * 1.10

df['単価'].apply(tax)

0      858.0
1       99.0
2      858.0
3      660.0
4      660.0
       ...
195    660.0
196     99.0
197    363.0
198    462.0
199    132.0
Name: 単価, Length: 200, dtype: float64

In [29]:
df['単価'] * 1.10

0      858.0
1       99.0
2      858.0
3      660.0
4      660.0
       ...
195    660.0
196     99.0
197    363.0
198    462.0
199    132.0
Name: 単価, Length: 200, dtype: float64

In [30]:
type(df['発注日'].loc[0])

str

In [38]:
type(pd.to_datetime(df['発注日']).loc[0])

pandas._libs.tslibs.timestamps.Timestamp

In [39]:
df.agg({'発注日':['max', 'min']})

            発注日
max  2024-12-26
min  2015-01-02

In [33]:
tax_series = df['単価'].apply(tax)
tax_series.name = "単価（税込み）"
pd.concat([df, tax_series], axis=1)

            発注日      商品番号              商品名   単価  在庫  注文数  単価（税込み）
0    2016-03-06  YY4HAAZR  商品サンプル YY4HAAZR  780  20   24    858.0
1    2015-03-27  Z4WOOIYV  商品サンプル Z4WOOIYV   90  45   12     99.0
2    2017-05-31  YY4HAAZR  商品サンプル YY4HAAZR  780  10    0    858.0
3    2022-10-26  1QJFO8QY  商品サンプル 1QJFO8QY  600   5   24    660.0
4    2016-06-10  1QJFO8QY  商品サンプル 1QJFO8QY  600  40   24    660.0
..          ...       ...              ...  ...  ..  ...      ...
195  2021-08-02  1QJFO8QY  商品サンプル 1QJFO8QY  600  10   42    660.0
196  2019-05-28  X0ZE2ZMY  商品サンプル X0ZE2ZMY   90  45   30     99.0
197  2015-06-22  48XMJXKO  商品サンプル 48XMJXKO  330  50   36    363.0
198  2022-08-29  QRMOGNUU  商品サンプル QRMOGNUU  420  40   48    462.0
199  2016-08-07  8T7D5DQA  商品サンプル 8T7D5DQA  120   0   42    132.0

[200 rows x 7 columns]

In [35]:
category_df = pd.read_csv('category.csv')
category_df

       商品番号  カテゴリー
0  YY4HAAZR     弁当
1  Z4WOOIYV    飲料水
2  1QJFO8QY     弁当
3  MESUDVWQ    菓子類
4  S6RE8W6X  図書・新聞
5  X0ZE2ZMY    飲料水
6  8T7D5DQA    菓子類
7  48XMJXKO   デザート
8  QRMOGNUU     雑貨
9  2HSTCDWM   デザート

In [42]:
category_df = pd.read_csv('category.csv')


df = pd.merge(
    df,
    category_df[["商品番号", "カテゴリー"]],
    how="inner",
    on="商品番号",
)
df

            発注日      商品番号              商品名   単価  在庫  注文数 カテゴリー_x カテゴリー_y カテゴリー
0    2016-03-06  YY4HAAZR  商品サンプル YY4HAAZR  780  20   24      弁当      弁当    弁当
1    2015-03-27  Z4WOOIYV  商品サンプル Z4WOOIYV   90  45   12     飲料水     飲料水   飲料水
2    2017-05-31  YY4HAAZR  商品サンプル YY4HAAZR  780  10    0      弁当      弁当    弁当
3    2022-10-26  1QJFO8QY  商品サンプル 1QJFO8QY  600   5   24      弁当      弁当    弁当
4    2016-06-10  1QJFO8QY  商品サンプル 1QJFO8QY  600  40   24      弁当      弁当    弁当
..          ...       ...              ...  ...  ..  ...     ...     ...   ...
195  2021-08-02  1QJFO8QY  商品サンプル 1QJFO8QY  600  10   42      弁当      弁当    弁当
196  2019-05-28  X0ZE2ZMY  商品サンプル X0ZE2ZMY   90  45   30     飲料水     飲料水   飲料水
197  2015-06-22  48XMJXKO  商品サンプル 48XMJXKO  330  50   36    デザート    デザート  デザート
198  2022-08-29  QRMOGNUU  商品サンプル QRMOGNUU  420  40   48      雑貨      雑貨    雑貨
199  2016-08-07  8T7D5DQA  商品サンプル 8T7D5DQA  120   0   42     菓子類     菓子類   菓子類

[200 rows x 9 columns]